const DAYS=[['ISNIN','Isnin'],['SELASA','Selasa'],['RABU','Rabu'],['KHAMIS','Khamis'],['JUMAAT','Jumaat']];
const $=id=>document.getElementById(id);const state={};
function iso(date){return date.toISOString().slice(0,10)}function toMonday(date){const d=new Date(date);const day=d.getDay()||7;d.setDate(d.getDate()-day+1);return d}function msDate(date){return new Intl.DateTimeFormat('ms-MY',{weekday:'long',day:'numeric',month:'long'}).format(date)}
function initialise(){for(let n=1;n<=45;n++)$('week').add(new Option(`Minggu ${n}`,n));const monday=toMonday(new Date());$('monday').value=iso(monday);$('week').value=String(getIsoWeek(monday));renderDays();$('monday').addEventListener('change',()=>{const selected=new Date($('monday').value+'T12:00:00');$('monday').value=iso(toMonday(selected));renderDays()});$('selectAll').addEventListener('click',()=>{document.querySelectorAll('[data-day]').forEach(el=>el.checked=true)});$('generateButton').addEventListener('click',generate)}
function getIsoWeek(d){const x=new Date(Date.UTC(d.getFullYear(),d.getMonth(),d.getDate()));const day=x.getUTCDay()||7;x.setUTCDate(x.getUTCDate()+4-day);const y=new Date(Date.UTC(x.getUTCFullYear(),0,1));return Math.ceil((((x-y)/86400000)+1)/7)}
function renderDays(){const monday=new Date($('monday').value+'T12:00:00');$('mondayHint').textContent=`Minggu ini bermula ${msDate(monday)}.`;$('daysList').innerHTML=DAYS.map(([key,label],i)=>{const date=new Date(monday);date.setDate(monday.getDate()+i);return `<div class="day-row"><div class="day-date"><strong>${label}</strong><span>${msDate(date)}</span></div><label class="switch"><input data-day="${key}" type="checkbox" checked aria-label="Jana ${label}"><span class="slider"></span></label></div>`}).join('')}
async function generate(){const days=Object.fromEntries([...document.querySelectorAll('[data-day]')].map(input=>[input.dataset.day,input.checked]));if(!Object.values(days).some(Boolean)){showStatus('Pilih sekurang-kurangnya satu hari','Tandakan hari yang hendak dijana.',false);return}$('generateButton').disabled=true;showStatus('AI sedang menjana eRPH','Semua slot bagi hari yang dipilih sedang diproses.',true);try{const response=await fetch('/api/generate-erph',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({week:Number($('week').value),monday:$('monday').value,days})});const result=await response.json();if(!result||!result.ok)throw new Error(result?.error||'Penjanaan eRPH gagal.');const summary=result.summary&&typeof result.summary==='object'?result.summary:{};const detail=Object.entries(summary).map(([day,count])=>`${day}: ${count} slot`).join(' · ');showStatus('eRPH berjaya dijana',`${result.generatedSlots||0} slot siap.${detail?' '+detail:''}`,false)}catch(error){showStatus('Penjanaan tidak berjaya',error.message||'Sila semak sambungan dan cuba lagi.',false)}finally{$('generateButton').disabled=false}}
function showStatus(title,text,loading){$('statusCard').classList.remove('hidden');$('statusTitle').textContent=title;$('statusText').textContent=text;$('spinner').style.display=loading?'block':'none'}
initialise();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');
